/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.me.mybackgroundapp;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HIOP
 */
public class ImageDisplay extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplay
     */
    public ImageDisplay() {
        initComponents();
        porfoco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ED_supply1 = new javax.swing.JTextField();
        MS_supply1 = new javax.swing.JTextField();
        RP_supply1 = new javax.swing.JTextField();
        Quinto_supply1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ED_supply2 = new javax.swing.JTextField();
        MS_supply2 = new javax.swing.JTextField();
        RP_supply2 = new javax.swing.JTextField();
        Quinto_supply2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ED_supply3 = new javax.swing.JTextField();
        MS_supply3 = new javax.swing.JTextField();
        RP_supply3 = new javax.swing.JTextField();
        Quinto_supply3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        total_supply_ED = new javax.swing.JTextField();
        total_supply_MS = new javax.swing.JTextField();
        total_supply_RP = new javax.swing.JTextField();
        total_supply_Quinto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Valor_Prey = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Valor_TC = new javax.swing.JTextField();
        Calcular_PreyTC = new javax.swing.JButton();
        PreyTC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Balance = new javax.swing.JTextField();
        Profit = new javax.swing.JTextField();
        lb_profit = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        ptx = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        arquivo = new javax.swing.JTextField();
        nomeED = new javax.swing.JTextField();
        nomeMS = new javax.swing.JTextField();
        nomeRP = new javax.swing.JTextField();
        nomeQuinto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculdora Loot v1.0");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(1024, 450, 450, 450));
        setMaximumSize(new java.awt.Dimension(999, 579));
        setMinimumSize(new java.awt.Dimension(999, 579));
        setPreferredSize(new java.awt.Dimension(999, 579));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel3.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel3.setText("ED:");

        jLabel4.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel4.setText("MS:");

        jLabel5.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel5.setText("RP:");

        jLabel6.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel6.setText("5º:");

        ED_supply1.setBackground(new java.awt.Color(255, 255, 204));
        ED_supply1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ED_supply1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ED_supply1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ED_supply1FocusLost(evt);
            }
        });
        ED_supply1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ED_supply1KeyReleased(evt);
            }
        });

        MS_supply1.setBackground(new java.awt.Color(255, 255, 204));
        MS_supply1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MS_supply1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MS_supply1FocusLost(evt);
            }
        });
        MS_supply1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MS_supply1KeyReleased(evt);
            }
        });

        RP_supply1.setBackground(new java.awt.Color(255, 255, 204));
        RP_supply1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RP_supply1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RP_supply1FocusLost(evt);
            }
        });
        RP_supply1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RP_supply1KeyReleased(evt);
            }
        });

        Quinto_supply1.setBackground(new java.awt.Color(255, 255, 204));
        Quinto_supply1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Quinto_supply1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Quinto_supply1FocusLost(evt);
            }
        });
        Quinto_supply1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Quinto_supply1KeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Supply");

        jLabel8.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Supply");

        ED_supply2.setBackground(new java.awt.Color(255, 255, 204));
        ED_supply2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ED_supply2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ED_supply2FocusLost(evt);
            }
        });
        ED_supply2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ED_supply2ActionPerformed(evt);
            }
        });
        ED_supply2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ED_supply2KeyReleased(evt);
            }
        });

        MS_supply2.setBackground(new java.awt.Color(255, 255, 204));
        MS_supply2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MS_supply2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MS_supply2FocusLost(evt);
            }
        });
        MS_supply2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MS_supply2KeyReleased(evt);
            }
        });

        RP_supply2.setBackground(new java.awt.Color(255, 255, 204));
        RP_supply2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RP_supply2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RP_supply2FocusLost(evt);
            }
        });
        RP_supply2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RP_supply2KeyReleased(evt);
            }
        });

        Quinto_supply2.setBackground(new java.awt.Color(255, 255, 204));
        Quinto_supply2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Quinto_supply2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Quinto_supply2FocusLost(evt);
            }
        });
        Quinto_supply2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Quinto_supply2KeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Supply");

        ED_supply3.setBackground(new java.awt.Color(255, 255, 204));
        ED_supply3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ED_supply3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ED_supply3FocusLost(evt);
            }
        });
        ED_supply3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ED_supply3ActionPerformed(evt);
            }
        });
        ED_supply3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ED_supply3KeyReleased(evt);
            }
        });

        MS_supply3.setBackground(new java.awt.Color(255, 255, 204));
        MS_supply3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MS_supply3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MS_supply3FocusLost(evt);
            }
        });
        MS_supply3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MS_supply3KeyReleased(evt);
            }
        });

        RP_supply3.setBackground(new java.awt.Color(255, 255, 204));
        RP_supply3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RP_supply3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RP_supply3FocusLost(evt);
            }
        });
        RP_supply3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RP_supply3KeyReleased(evt);
            }
        });

        Quinto_supply3.setBackground(new java.awt.Color(255, 255, 204));
        Quinto_supply3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Quinto_supply3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Quinto_supply3FocusLost(evt);
            }
        });
        Quinto_supply3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Quinto_supply3KeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total");

        total_supply_ED.setEditable(false);
        total_supply_ED.setBackground(new java.awt.Color(255, 255, 204));
        total_supply_ED.setText("0");
        total_supply_ED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_supply_EDActionPerformed(evt);
            }
        });

        total_supply_MS.setEditable(false);
        total_supply_MS.setBackground(new java.awt.Color(255, 255, 204));
        total_supply_MS.setText("0");

        total_supply_RP.setEditable(false);
        total_supply_RP.setBackground(new java.awt.Color(255, 255, 204));
        total_supply_RP.setText("0");

        total_supply_Quinto.setEditable(false);
        total_supply_Quinto.setBackground(new java.awt.Color(255, 255, 204));
        total_supply_Quinto.setText("0");

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prey e TC"));
        jPanel2.setName(""); // NOI18N

        Valor_Prey.setBackground(new java.awt.Color(255, 255, 204));
        Valor_Prey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Valor_PreyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Valor_PreyFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Prey Cards:");

        jLabel12.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Tibia Coins:");

        Valor_TC.setBackground(new java.awt.Color(255, 255, 204));
        Valor_TC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Valor_TCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Valor_TCFocusLost(evt);
            }
        });

        Calcular_PreyTC.setText("Calcular");
        Calcular_PreyTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular_PreyTCActionPerformed(evt);
            }
        });

        PreyTC.setEditable(false);
        PreyTC.setBackground(new java.awt.Color(255, 255, 204));
        PreyTC.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Calcular_PreyTC))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Valor_Prey, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valor_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreyTC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Valor_Prey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Valor_TC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreyTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calcular_PreyTC))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel13.setText("Balance:");

        Balance.setBackground(new java.awt.Color(255, 255, 204));
        Balance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BalanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BalanceFocusLost(evt);
            }
        });
        Balance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BalanceKeyReleased(evt);
            }
        });

        Profit.setEditable(false);
        Profit.setBackground(java.awt.Color.yellow);
        Profit.setText("0");

        lb_profit.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        lb_profit.setForeground(java.awt.Color.cyan);
        lb_profit.setText("Profit");

        Salvar.setBackground(new java.awt.Color(0, 204, 204));
        Salvar.setText("SALVAR");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        ptx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PT x:", "2", "3", "4", "5" }));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Limpar Tela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Wide Latin", 2, 10)); // NOI18N
        jLabel15.setText("Nome Arquvo:");

        arquivo.setBackground(new java.awt.Color(255, 255, 204));
        arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoActionPerformed(evt);
            }
        });

        nomeED.setBackground(new java.awt.Color(255, 255, 204));
        nomeED.setToolTipText("Digite o nome do ED");
        nomeED.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeEDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeEDFocusLost(evt);
            }
        });
        nomeED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEDActionPerformed(evt);
            }
        });

        nomeMS.setBackground(new java.awt.Color(255, 255, 204));
        nomeMS.setToolTipText("Digite o nome do MS");
        nomeMS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeMSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeMSFocusLost(evt);
            }
        });
        nomeMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMSActionPerformed(evt);
            }
        });

        nomeRP.setBackground(new java.awt.Color(255, 255, 204));
        nomeRP.setToolTipText("Digite o nome do RP");
        nomeRP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeRPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeRPFocusLost(evt);
            }
        });
        nomeRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeRPActionPerformed(evt);
            }
        });

        nomeQuinto.setBackground(new java.awt.Color(255, 255, 204));
        nomeQuinto.setToolTipText("Digite o nome do Quinto");
        nomeQuinto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeQuintoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeQuintoFocusLost(evt);
            }
        });
        nomeQuinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeQuintoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Wide Latin", 2, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeMS, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeRP, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RP_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RP_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeED, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MS_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ED_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ED_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MS_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nomeQuinto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Quinto_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Quinto_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel14)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ED_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(total_supply_ED, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MS_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(total_supply_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RP_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(total_supply_RP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_profit)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Quinto_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_supply_Quinto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Profit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(258, 258, 258))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ptx, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(texto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(ptx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ED_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ED_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ED_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_supply_ED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_supply_MS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MS_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(MS_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MS_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RP_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(RP_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RP_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_supply_RP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quinto_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Quinto_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quinto_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_supply_Quinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeQuinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_profit)
                    .addComponent(Profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(texto)
                .addContainerGap())
        );

        nomeED.getAccessibleContext().setAccessibleName("Digite o nome do ED");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/mybackgroundapp/newpackage/testar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -1, 1030, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void total_supply_EDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_supply_EDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_supply_EDActionPerformed

    private void Calcular_PreyTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular_PreyTCActionPerformed
        int prey = Integer.parseInt(Valor_Prey.getText());
        double tc = Double.parseDouble(Valor_TC.getText());
        double calculo = (prey * 10) * tc;
        PreyTC.setText(calculo + "");
        double balance = Integer.parseInt(Balance.getText());
        double desconto = balance - calculo;
        Balance.setText(desconto + "");
        Balance();
    }//GEN-LAST:event_Calcular_PreyTCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ED_supply1.setText("0");
        ED_supply2.setText("0");
        ED_supply3.setText("0");
        total_supply_ED.setText("0");
        MS_supply1.setText("0");
        MS_supply1.setText("0");
        MS_supply1.setText("0");
        total_supply_MS.setText("0");
        RP_supply1.setText("0");
        RP_supply1.setText("0");
        RP_supply1.setText("0");
        total_supply_RP.setText("0");
        Quinto_supply1.setText("0");
        Quinto_supply1.setText("0");
        Quinto_supply1.setText("0");
        total_supply_Quinto.setText("0");
        Balance.setText("0");
        Valor_Prey.setText("0");
        Valor_TC.setText("0");
        Profit.setText("0");
        ptx.setSelectedIndex(0);
        lb_profit.setForeground(Color.cyan);
        Profit.setBackground(Color.yellow);
        texto.setText("");
        arquivo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        try {
            Date hoje = new Date();
            SimpleDateFormat df;
            double supplyED = Double.parseDouble(total_supply_ED.getText());
            double supplyMS = Double.parseDouble(total_supply_MS.getText());
            double supplyRP = Double.parseDouble(total_supply_RP.getText());
            double supplyQuinto = Double.parseDouble(total_supply_Quinto.getText());
            df = new SimpleDateFormat("dd_MM_yyyy HH.mm.ss");
            FileWriter arq = new FileWriter("C:\\Hunts-Tibia\\" + arquivo.getText() + " " + df.format(hoje) + ".txt");
            PrintWriter gravarArq = new PrintWriter(arq);

            gravarArq.printf("******WASTES******\r\n" + "\r\n");
            gravarArq.printf("Waste " + nomeED.getText() + ": " + supplyED + "\r\n");
            gravarArq.printf("Waste " + nomeMS.getText() + ": " + supplyMS + "\r\n");
            gravarArq.printf("Waste " + nomeRP.getText() + ": " + supplyRP + "\r\n");
            gravarArq.printf("Waste " + nomeQuinto.getText() + ": " + supplyQuinto + "\r\n" + "\r\n");
            gravarArq.printf("******PROFITS******\r\n" + "\r\n");
            gravarArq.printf("Balance: " + Balance.getText() + "\r\n");
            gravarArq.printf("Gastos em Prey: " + PreyTC.getText() + "\r\n");
            gravarArq.printf("Profit: " + Profit.getText() + "\r\n" + "\r\n");
            gravarArq.printf("******TOTAL A PAGAR******\r\n" + "\r\n");
            double profit = Double.parseDouble(Profit.getText() + "\r\n");

            double contaED = supplyED + profit;
            double contaMS = supplyMS + profit;
            double contaRP = supplyRP + profit;
            double contaQuinto = supplyQuinto + profit;
            gravarArq.printf(nomeED.getText() + ": " + contaED + "\r\n");
            gravarArq.printf(nomeMS.getText() + ": " + contaMS + "\r\n");
            gravarArq.printf(nomeRP.getText() + ": " + contaRP + "\r\n");
            gravarArq.printf(nomeQuinto.getText() + ": " + contaQuinto + "\r\n");
            arq.close();
            texto.setForeground(Color.green);
            texto.setText("Arquivo Salvo com Sucesso!!");
        } catch (IOException ex) {
            Logger.getLogger(ImageDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void arquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquivoActionPerformed

    private void nomeEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEDActionPerformed

    }//GEN-LAST:event_nomeEDActionPerformed

    private void nomeMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMSActionPerformed

    private void nomeRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeRPActionPerformed

    private void nomeQuintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeQuintoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeQuintoActionPerformed

    private void ED_supply1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ED_supply1KeyReleased

        CalcularSupplyED();
    }//GEN-LAST:event_ED_supply1KeyReleased

    private void ED_supply2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ED_supply2ActionPerformed

    }//GEN-LAST:event_ED_supply2ActionPerformed

    private void ED_supply3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ED_supply3ActionPerformed

    }//GEN-LAST:event_ED_supply3ActionPerformed

    private void ED_supply2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ED_supply2KeyReleased
        CalcularSupplyED();
    }//GEN-LAST:event_ED_supply2KeyReleased

    private void ED_supply3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ED_supply3KeyReleased
        CalcularSupplyED();
    }//GEN-LAST:event_ED_supply3KeyReleased

    private void MS_supply1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MS_supply1KeyReleased
        CalcularSupplyMS();
    }//GEN-LAST:event_MS_supply1KeyReleased

    private void nomeEDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeEDFocusGained

        if (nomeED.getText().equals("Digite o nome do ED")) {
            nomeED.setText("");
        }
    }//GEN-LAST:event_nomeEDFocusGained

    private void nomeEDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeEDFocusLost
        if (nomeED.getText().equals("")) {
            nomeED.setText("Digite o nome do ED");
        }
    }//GEN-LAST:event_nomeEDFocusLost

    private void nomeMSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeMSFocusLost
        if (nomeMS.getText().equals("")) {
            nomeMS.setText("Ensira o nome do MS");
        }
    }//GEN-LAST:event_nomeMSFocusLost

    private void nomeMSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeMSFocusGained
        if (nomeMS.getText().equals("Ensira o nome do MS")) {
            nomeMS.setText("");
        }
    }//GEN-LAST:event_nomeMSFocusGained

    private void RP_supply1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RP_supply1FocusGained
        if (RP_supply1.getText().equals("0")) {
            RP_supply1.setText("");
        }
    }//GEN-LAST:event_RP_supply1FocusGained

    private void nomeRPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeRPFocusLost
        if (nomeRP.getText().equals("")) {
            nomeRP.setText("Ensira o nome do RP");
    }//GEN-LAST:event_nomeRPFocusLost
    }

    private void nomeRPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeRPFocusGained
        if (nomeRP.getText().equals("Ensira o nome do RP")) {
            nomeRP.setText("");
        }
    }//GEN-LAST:event_nomeRPFocusGained

    private void nomeQuintoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeQuintoFocusGained
        if (nomeQuinto.getText().equals("Ensira o nome do 5°")) {
            nomeQuinto.setText("");
        }
    }//GEN-LAST:event_nomeQuintoFocusGained

    private void nomeQuintoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeQuintoFocusLost
        if (nomeQuinto.getText().equals("")) {
            nomeQuinto.setText("Ensira o nome do 5°");
        }
    }//GEN-LAST:event_nomeQuintoFocusLost

    private void RP_supply1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RP_supply1FocusLost
        if (RP_supply1.getText().equals("")) {
            RP_supply1.setText("0");
        }
    }//GEN-LAST:event_RP_supply1FocusLost

    private void RP_supply2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RP_supply2FocusGained
        if (RP_supply2.getText().equals("0")) {
            RP_supply2.setText("");
        }
    }//GEN-LAST:event_RP_supply2FocusGained

    private void MS_supply2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MS_supply2KeyReleased
        CalcularSupplyMS();
    }//GEN-LAST:event_MS_supply2KeyReleased

    private void MS_supply3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MS_supply3KeyReleased
        CalcularSupplyMS();
    }//GEN-LAST:event_MS_supply3KeyReleased

    private void RP_supply1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RP_supply1KeyReleased
        CalcularSupplyRP();
    }//GEN-LAST:event_RP_supply1KeyReleased

    private void RP_supply2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RP_supply2KeyReleased
        CalcularSupplyRP();
    }//GEN-LAST:event_RP_supply2KeyReleased

    private void RP_supply3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RP_supply3KeyReleased
        CalcularSupplyRP();
    }//GEN-LAST:event_RP_supply3KeyReleased

    private void Quinto_supply1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Quinto_supply1KeyReleased
        CalcularSupplyQuinto();
    }//GEN-LAST:event_Quinto_supply1KeyReleased

    private void Quinto_supply2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Quinto_supply2KeyReleased
        CalcularSupplyQuinto();
    }//GEN-LAST:event_Quinto_supply2KeyReleased

    private void Quinto_supply3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Quinto_supply3KeyReleased
        CalcularSupplyQuinto();
    }//GEN-LAST:event_Quinto_supply3KeyReleased

    private void ED_supply1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ED_supply1FocusGained
        if (ED_supply1.getText().equals("0")) {
            ED_supply1.setText("");
        }
    }//GEN-LAST:event_ED_supply1FocusGained

    private void ED_supply1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ED_supply1FocusLost
        if (ED_supply1.getText().equals("")) {
            ED_supply1.setText("0");
        }
    }//GEN-LAST:event_ED_supply1FocusLost

    private void ED_supply2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ED_supply2FocusGained
        if (ED_supply2.getText().equals("0")) {
            ED_supply2.setText("");
        }
    }//GEN-LAST:event_ED_supply2FocusGained

    private void ED_supply2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ED_supply2FocusLost
        if (ED_supply2.getText().equals("")) {
            ED_supply2.setText("0");
        }
    }//GEN-LAST:event_ED_supply2FocusLost

    private void ED_supply3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ED_supply3FocusGained
        if (ED_supply3.getText().equals("0")) {
            ED_supply3.setText("");
        }
    }//GEN-LAST:event_ED_supply3FocusGained

    private void ED_supply3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ED_supply3FocusLost
        if (ED_supply3.getText().equals("")) {
            ED_supply3.setText("0");
        }
    }//GEN-LAST:event_ED_supply3FocusLost

    private void MS_supply1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MS_supply1FocusGained
        if (MS_supply1.getText().equals("0")) {
            MS_supply1.setText("");
        }
    }//GEN-LAST:event_MS_supply1FocusGained

    private void MS_supply1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MS_supply1FocusLost
        if (MS_supply1.getText().equals("")) {
            MS_supply1.setText("0");
        }
    }//GEN-LAST:event_MS_supply1FocusLost

    private void MS_supply2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MS_supply2FocusGained
        if (MS_supply2.getText().equals("0")) {
            MS_supply2.setText("");
        }
    }//GEN-LAST:event_MS_supply2FocusGained

    private void MS_supply2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MS_supply2FocusLost
        if (MS_supply2.getText().equals("")) {
            MS_supply2.setText("0");
        }
    }//GEN-LAST:event_MS_supply2FocusLost

    private void MS_supply3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MS_supply3FocusGained
        if (MS_supply3.getText().equals("0")) {
            MS_supply3.setText("");
        }
    }//GEN-LAST:event_MS_supply3FocusGained

    private void MS_supply3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MS_supply3FocusLost
        if (MS_supply3.getText().equals("")) {
            MS_supply3.setText("0");
        }
    }//GEN-LAST:event_MS_supply3FocusLost

    private void RP_supply2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RP_supply2FocusLost
        if (RP_supply2.getText().equals("")) {
            RP_supply2.setText("0");
        }
    }//GEN-LAST:event_RP_supply2FocusLost

    private void RP_supply3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RP_supply3FocusGained
        if (RP_supply3.getText().equals("0")) {
            RP_supply3.setText("");
        }
    }//GEN-LAST:event_RP_supply3FocusGained

    private void RP_supply3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RP_supply3FocusLost
        if (RP_supply3.getText().equals("")) {
            RP_supply3.setText("0");
        }
    }//GEN-LAST:event_RP_supply3FocusLost

    private void Quinto_supply1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Quinto_supply1FocusGained
        if (Quinto_supply1.getText().equals("0")) {
            Quinto_supply1.setText("");
        }
    }//GEN-LAST:event_Quinto_supply1FocusGained

    private void Quinto_supply1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Quinto_supply1FocusLost
        if (Quinto_supply1.getText().equals("")) {
            Quinto_supply1.setText("0");
        }
    }//GEN-LAST:event_Quinto_supply1FocusLost

    private void Quinto_supply2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Quinto_supply2FocusGained
        if (Quinto_supply2.getText().equals("0")) {
            Quinto_supply2.setText("");
        }
    }//GEN-LAST:event_Quinto_supply2FocusGained

    private void Quinto_supply2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Quinto_supply2FocusLost
        if (Quinto_supply2.getText().equals("")) {
            Quinto_supply2.setText("0");
        }
    }//GEN-LAST:event_Quinto_supply2FocusLost

    private void Quinto_supply3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Quinto_supply3FocusGained
        if (Quinto_supply3.getText().equals("0")) {
            Quinto_supply3.setText("");
        }
    }//GEN-LAST:event_Quinto_supply3FocusGained

    private void Quinto_supply3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Quinto_supply3FocusLost
        if (Quinto_supply3.getText().equals("")) {
            Quinto_supply3.setText("0");
        }
    }//GEN-LAST:event_Quinto_supply3FocusLost

    private void BalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BalanceFocusGained
        if (Balance.getText().equals("0")) {
            Balance.setText("");
        }
    }//GEN-LAST:event_BalanceFocusGained

    private void BalanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BalanceFocusLost
        if (Balance.getText().equals("")) {
            Balance.setText("0");
        }
    }//GEN-LAST:event_BalanceFocusLost

    private void Valor_PreyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Valor_PreyFocusGained
        if (Valor_Prey.getText().equals("0")) {
            Valor_Prey.setText("");
        }
    }//GEN-LAST:event_Valor_PreyFocusGained

    private void Valor_PreyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Valor_PreyFocusLost
        if (Valor_Prey.getText().equals("")) {
            Valor_Prey.setText("0");
        }
    }//GEN-LAST:event_Valor_PreyFocusLost

    private void Valor_TCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Valor_TCFocusGained
        if (Valor_TC.getText().equals("0")) {
            Valor_TC.setText("");
        }
    }//GEN-LAST:event_Valor_TCFocusGained

    private void Valor_TCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Valor_TCFocusLost
        if (Valor_TC.getText().equals("")) {
            Valor_TC.setText("0");
        }
    }//GEN-LAST:event_Valor_TCFocusLost

    private void BalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BalanceKeyReleased
        Balance();
    }//GEN-LAST:event_BalanceKeyReleased


    public void Balance() {
        double supplyED = Double.parseDouble(total_supply_ED.getText());
        double supplyMS = Double.parseDouble(total_supply_MS.getText());
        double supplyRP = Double.parseDouble(total_supply_RP.getText());
        double supplyQuinto = Double.parseDouble(total_supply_Quinto.getText());
        double balance = Double.parseDouble(Balance.getText());
        double calculo = supplyED + supplyMS + supplyRP + supplyQuinto;

        DecimalFormat df = new DecimalFormat("0.##");
        if (ptx.getSelectedIndex() == 1) {
            double divisao = (balance - calculo) / 2;
            String dx = df.format(divisao);
            Profit.setText("" + divisao);
            Cor();
        }
        if (ptx.getSelectedIndex() == 2) {
            double divisao = (balance - calculo) / 3;
            String dx = df.format(divisao);
            Profit.setText("" + divisao);
            Cor();
        }
        if (ptx.getSelectedIndex() == 3) {
            double divisao = (balance - calculo) / 4;
            String dx = df.format(divisao);
            Profit.setText("" + divisao);
            Cor();
        }
        if (ptx.getSelectedIndex() == 4) {
            double divisao = (balance - calculo) / 5;
            String dx = df.format(divisao);
            Profit.setText("" + divisao);
            Cor();
        }
    }

    public void porfoco() {
        nomeED.requestFocus();
        nomeMS.setText("Ensira o nome do MS");
        nomeRP.setText("Ensira o nome do RP");
        nomeQuinto.setText("Ensira o nome do 5°");
        ED_supply1.setText("0");
        ED_supply2.setText("0");
        ED_supply3.setText("0");
        MS_supply1.setText("0");
        MS_supply2.setText("0");
        MS_supply3.setText("0");
        RP_supply1.setText("0");
        RP_supply2.setText("0");
        RP_supply3.setText("0");
        Quinto_supply1.setText("0");
        Quinto_supply2.setText("0");
        Quinto_supply3.setText("0");
        Balance.setText("0");
        Valor_Prey.setText("0");
        Valor_TC.setText("0");
    }

    public void CalcularSupplyED() {
        int supply1 = Integer.parseInt(ED_supply1.getText());
        int supply2 = Integer.parseInt(ED_supply2.getText());
        int supply3 = Integer.parseInt(ED_supply3.getText());
        double calculo = supply1 + supply2 + supply3;
        total_supply_ED.setText("" + calculo);
    }

    public void CalcularSupplyMS() {
        int supply1 = Integer.parseInt(MS_supply1.getText());
        int supply2 = Integer.parseInt(MS_supply2.getText());
        int supply3 = Integer.parseInt(MS_supply3.getText());
        double calculo = supply1 + supply2 + supply3;
        total_supply_MS.setText("" + calculo);
    }

    public void CalcularSupplyRP() {
        int supply1 = Integer.parseInt(RP_supply1.getText());
        int supply2 = Integer.parseInt(RP_supply2.getText());
        int supply3 = Integer.parseInt(RP_supply3.getText());
        double calculo = supply1 + supply2 + supply3;
        total_supply_RP.setText("" + calculo);
    }

    public void CalcularSupplyQuinto() {
        int supply1 = Integer.parseInt(Quinto_supply1.getText());
        int supply2 = Integer.parseInt(Quinto_supply2.getText());
        int supply3 = Integer.parseInt(Quinto_supply3.getText());
        double calculo = supply1 + supply2 + supply3;
        total_supply_Quinto.setText("" + calculo);
    }

    public void Cor() {
        double profit = Double.parseDouble(Profit.getText());
        if (profit > 0) {
            lb_profit.setForeground(Color.green);
            Profit.setBackground(Color.green);
        } else {
            if (profit < 0) {
                lb_profit.setForeground(Color.red);
                Profit.setBackground(Color.red);
            } else {
                lb_profit.setForeground(Color.cyan);
                Profit.setBackground(Color.yellow);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Balance;
    private javax.swing.JButton Calcular_PreyTC;
    private javax.swing.JTextField ED_supply1;
    private javax.swing.JTextField ED_supply2;
    private javax.swing.JTextField ED_supply3;
    private javax.swing.JTextField MS_supply1;
    private javax.swing.JTextField MS_supply2;
    private javax.swing.JTextField MS_supply3;
    private javax.swing.JTextField PreyTC;
    private javax.swing.JTextField Profit;
    private javax.swing.JTextField Quinto_supply1;
    private javax.swing.JTextField Quinto_supply2;
    private javax.swing.JTextField Quinto_supply3;
    private javax.swing.JTextField RP_supply1;
    private javax.swing.JTextField RP_supply2;
    private javax.swing.JTextField RP_supply3;
    private javax.swing.JButton Salvar;
    private javax.swing.JTextField Valor_Prey;
    private javax.swing.JTextField Valor_TC;
    private javax.swing.JTextField arquivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_profit;
    private javax.swing.JTextField nomeED;
    private javax.swing.JTextField nomeMS;
    private javax.swing.JTextField nomeQuinto;
    private javax.swing.JTextField nomeRP;
    private javax.swing.JComboBox<String> ptx;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField total_supply_ED;
    private javax.swing.JTextField total_supply_MS;
    private javax.swing.JTextField total_supply_Quinto;
    private javax.swing.JTextField total_supply_RP;
    // End of variables declaration//GEN-END:variables
}
